### ISSUE TITLE
同一个页面同时引入两个popup组件，前一个show属性传true，后一个show属性传false，两个组件都无法展示。

### ISSUE THREAD

**Issue by jianyuanzong** [hummer-home/tenon-plugins#4]
## 描述
同一个页面同时引入两个popup组件，前一个show属性传true，后一个show属性传false，iOS 中两个组件都无法展示。

## Hummer version: 

@hummer/vue-plugin-popup@^0.2.0

## 复现步骤

1.同一个页面引用两个popup组件，两个组件都show属性都传true。
2.一段时间后其中一个 show属性设为false
## 预期结果

两个组件互补干扰，独立展示

**Comment by duanlikang** [comment]
问题原因：
由于 iOS 中多个Dialog实例存在时，会进行覆盖，具体issure可以参考 [hummer issure 103](https://github.com/didi/Hummer/issues/103)。

临时修复方案：
在 popup组件使用时，同时增加上 `v-if`控制是否创建popup组件，保证同时存在一个实例。在组件销毁的生命周期中，手动调用popup组件的`dismissDialog`方法，进行弹窗的释放。
